# Name your workflow
name: Node.js CI/CD

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ] # e.g., v1.0.0, v2.3.4
  pull_request:
    branches: [ main ]

# (Optional) Cancel previous runs on the same branch that are in progress
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Define the jobs that will run
jobs:
  # ----------------------------------------
  # 1. TEST JOB (WITH MATRIX)
  # ----------------------------------------
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define the matrix strategy for parallel testing
    strategy:
      matrix:
        node-version: [18 , 20] # Runs a job for each version

    steps:
      # Step 1: Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the specific Node.js version for this matrix job
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Speeds up dependency installation

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci # 'ci' is faster and safer for automated environments

      # Step 4: Run your tests (assuming 'npm test' is defined in package.json)
      - name: Run tests
        run: npm test

      # Step 5: Upload test results artifact for this specific Node version
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node-version }} # Unique name for each job's artifact
          path: test-results/ # The folder containing your results

  # ----------------------------------------
  # 2. BUILD JOB (CONDITIONAL)
  # ----------------------------------------
  build:
    # The build job will only run on an ubuntu runner
    runs-on: ubuntu-latest
    
    # This job needs the 'test' job to complete successfully for all matrix versions
    needs: test

    # This is the crucial condition for when to run the build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')

    # (Optional) Add this for manual approval before creating the artifact
    environment:
      name: production
      url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      # Step 1: Check out your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (you can pick one version for the build)
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the build script (assuming 'npm run build' is defined)
      - name: Build project
        run: npm run build

      # Step 5: Upload the build output artifact
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files # Name of the final build artifact
          path: dist/ # The folder containing your build output
